name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'gip-inclusion/les-emplois'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto ${{github.event.pull_request.number}}
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
